// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tawpbmncsxsaajmhqrfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhd3BibW5jc3hzYWFqbWhxcmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzODUzNDQsImV4cCI6MjA0OTk2MTM0NH0.P3YvHYVl_JnqD4qorglVm74IUSH460OKy2myefClD_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);